<?php

/**
 * @see https://github.com/artesaos/seotools
 */

return [
    'meta' => [
        /*
         * The default configurations to be used by the meta generator.
         */
        'defaults'       => [
            'title'        => false, //"It's Over 9000!", // set false to total remove
            'titleBefore'  => false, // Put defaults.title before page title, like 'It's Over 9000! - Dashboard'
            'description'  => false, //'For those who helped create the Genki Dama', // set false to total remove
            'separator'    => ' - ',
            'keywords'     => [
                "Rumah mewah di Pekanbaru",
                "Hunian nyaman di Pekanbaru",
                "Properti modern Pekanbaru",
                "Perumahan elit Pekanbaru",
                "Rumah asri di Pekanbaru",
                "Kompleks perumahan Pekanbaru",
                "Perumahan hijau Pekanbaru",
                "Hunian ramah lingkungan Pekanbaru",
                "Rumah minimalis Pekanbaru",
                "Properti strategis Pekanbaru",
                "Rumah idaman Pekanbaru",
                "Perumahan nyaman Pekanbaru",
                "Rumah premium Pekanbaru",
                "Properti keluarga Pekanbaru",
                "Perumahan modern Pekanbaru",
                "Hunian eksklusif Pekanbaru",
                "Properti nyaman Pekanbaru",
                "Rumah eksklusif Pekanbaru",
                "Hunian hijau Pekanbaru",
                "Rumah aman Pekanbaru",
                "Properti elit Pekanbaru",
                "Perumahan asri Pekanbaru",
                "Rumah keluarga Pekanbaru",
                "Properti hijau Pekanbaru",
                "Perumahan premium Pekanbaru",
                "Hunian strategis Pekanbaru",
                "Properti ramah lingkungan Pekanbaru",
                "Rumah hijau Pekanbaru",
                "Perumahan eksklusif Pekanbaru",
                "Hunian premium Pekanbaru",
                "Properti minimalis Pekanbaru",
                "Rumah strategis Pekanbaru",
                "Perumahan ramah lingkungan Pekanbaru",
                "Hunian aman Pekanbaru",
                "Properti asri Pekanbaru",
                "Rumah luas Pekanbaru",
                "Perumahan minimalis Pekanbaru",
                "Hunian modern Pekanbaru",
                "Properti aman Pekanbaru",
                "Rumah berkualitas Pekanbaru",
                "Perumahan strategis Pekanbaru",
                "Hunian nyaman Pekanbaru",
                "Properti modern dan asri Pekanbaru",
                "Rumah hijau dan asri Pekanbaru",
                "Perumahan elit dan nyaman Pekanbaru",
                "Hunian hijau dan nyaman Pekanbaru",
                "Properti premium dan asri Pekanbaru",
                "Rumah nyaman dan aman Pekanbaru",
                "Perumahan strategis dan asri Pekanbaru",
                "Hunian eksklusif dan asri Pekanbaru",
                "Properti modern dan nyaman Pekanbaru",
                "Rumah hijau dan aman Pekanbaru",
                "Perumahan elit dan hijau Pekanbaru",
                "Hunian hijau dan strategis Pekanbaru",
                "Properti strategis dan nyaman Pekanbaru",
                "Rumah minimalis dan asri Pekanbaru",
                "Perumahan premium dan nyaman Pekanbaru",
                "Hunian modern dan strategis Pekanbaru",
                "Properti eksklusif dan nyaman Pekanbaru",
                "Rumah hijau dan strategis Pekanbaru",
                "Perumahan minimalis dan hijau Pekanbaru",
                "Hunian strategis dan nyaman Pekanbaru",
                "Properti elit dan hijau Pekanbaru",
                "Rumah hijau dan nyaman Pekanbaru",
                "Perumahan modern dan hijau Pekanbaru",
                "Hunian minimalis dan strategis Pekanbaru",
                "Properti premium dan nyaman Pekanbaru",
                "Rumah hijau dan nyaman Pekanbaru",
                "Perumahan elit dan strategis Pekanbaru",
                "Hunian modern dan hijau Pekanbaru",
                "Properti strategis dan hijau Pekanbaru",
                "Rumah minimalis dan strategis Pekanbaru",
                "Perumahan eksklusif dan hijau Pekanbaru",
                "Hunian premium dan strategis Pekanbaru",
                "Properti elit dan nyaman Pekanbaru",
                "Rumah hijau dan strategis Pekanbaru",
                "Perumahan modern dan strategis Pekanbaru",
                "Hunian minimalis dan hijau Pekanbaru",
                "Properti strategis dan hijau Pekanbaru",
                "Rumah hijau dan strategis Pekanbaru",
                "Perumahan eksklusif dan nyaman Pekanbaru",
                "Hunian premium dan hijau Pekanbaru",
                "Properti elit dan strategis Pekanbaru",
                "Rumah hijau dan nyaman Pekanbaru",
                "Perumahan modern dan hijau Pekanbaru",
                "Hunian minimalis dan hijau Pekanbaru",
                "Properti strategis dan hijau Pekanbaru",
                "Rumah hijau dan strategis Pekanbaru",
                "Perumahan eksklusif dan hijau Pekanbaru",
                "Hunian premium dan strategis Pekanbaru",
                "Properti elit dan nyaman Pekanbaru",
                "Perumahan mewah Riau",
                "Hunian nyaman Riau",
                "Rumah modern Riau",
                "Properti asri Riau",
                "Rumah di alam Riau",
                "Komplek perumahan Riau",
                "Perumahan eksklusif Riau",
                "Rumah aman Riau",
                "Properti keluarga Riau",
                "Perumahan strategis Riau",
                "Rumah asri di Riau",
                "Perumahan elit Riau",
                "Hunian ramah lingkungan Riau",
                "Perumahan hijau Riau",
                "Perumahan alam Riau",
                "Properti premium Riau",
                "Rumah minimalis Riau",
                "Perumahan nuansa alam Riau",
                "Perumahan aman Riau",
                "Rumah berkualitas Riau",
                "Perumahan nyaman Riau",
                "Rumah modern minimalis Riau",
                "Perumahan luas Riau",
                "Hunian premium Riau",
                "Properti modern Riau",
                "Rumah eksklusif Riau",
                "Rumah idaman Riau",
                "Perumahan nyaman dan asri Riau",
                "Rumah nyaman di Riau",
                "Properti elit Riau",
                "Hunian eksklusif Riau",
                "Perumahan hijau dan asri Riau",
                "Rumah keluarga Riau",
                "Properti strategis Riau",
                "Rumah alam Riau",
                "Hunian elit Riau",
                "Perumahan mewah dan asri Riau",
                "Rumah dengan nuansa alam Riau",
                "Properti hijau Riau",
                "Hunian modern Riau",
                "Perumahan asri dan aman Riau",
                "Rumah eksklusif di alam Riau",
                "Properti nyaman Riau",
                "Perumahan asri di Riau",
                "Rumah premium di Riau",
                "Hunian nyaman dan asri Riau",
                "Properti idaman Riau",
                "Perumahan strategis dan asri Riau",
                "Rumah minimalis modern Riau",
                "Properti alam Riau",
                "Perumahan elit dan asri Riau",
                "Rumah ramah lingkungan Riau",
                "Hunian hijau Riau",
                "Perumahan berkualitas Riau",
                "Rumah hijau dan asri Riau",
                "Properti aman Riau",
                "Perumahan minimalis Riau",
                "Rumah elit di Riau",
                "Hunian hijau dan asri Riau",
                "Properti mewah Riau",
                "Rumah nyaman di alam Riau",
                "Perumahan nyaman dan hijau Riau",
                "Properti eksklusif Riau",
                "Rumah strategis Riau",
                "Perumahan hijau di Riau",
                "Rumah modern dan asri Riau",
                "Properti premium dan asri Riau",
                "Hunian strategis Riau",
                "Perumahan keluarga Riau",
                "Rumah nyaman dan aman Riau",
                "Properti elit dan asri Riau",
                "Perumahan minimalis dan asri Riau",
                "Rumah hijau di Riau",
                "Hunian premium dan asri Riau",
                "Perumahan eksklusif dan asri Riau",
                "Rumah modern dan nyaman Riau",
                "Properti aman dan asri Riau",
                "Perumahan berkualitas dan asri Riau",
                "Rumah elit dan nyaman Riau",
                "Hunian hijau dan nyaman Riau",
                "Perumahan minimalis dan hijau Riau",
                "Properti hijau dan asri Riau",
                "Rumah strategis dan asri Riau",
                "Hunian mewah dan asri Riau",
                "Perumahan hijau dan nyaman Riau",
                "Properti eksklusif dan asri Riau",
                "Rumah minimalis dan nyaman Riau",
                "Perumahan elit dan nyaman Riau",
                "Properti strategis dan asri Riau",
                "Rumah modern dan hijau Riau",
                "Hunian hijau dan aman Riau",
                "Perumahan berkualitas dan nyaman Riau",
                "Properti elit dan nyaman Riau",
                "Rumah hijau dan nyaman Riau",
                "Hunian strategis dan hijau Riau",
                "Perumahan minimalis dan hijau Riau",
                "Properti modern dan asri Riau",
                "Rumah hijau dan strategis Riau",
                "Hunian eksklusif dan nyaman Riau",
                "Perumahan premium dan hijau Riau",
                "asraya riau",
                "Pesona hutan asraya",
                "Atelier Riri asraya townhouse",
                "Pekanbaru asraya",
                "LIVING HARMONY IN NATURE",
                "Lokasi strategis riau",
                "Properti idaman pekanbaru riau",
                "Nilai investasi tinggi",
                "Premium cluster",
                "Rumah lokasi strategis",
                "Cicilan ringan",
                "Fasilitas berlimpah",
                "Kemudahan akses & transportasi",
                "Kawasan asri",
                "Perumahan elit dengan banyak fasilitas",
                "Perumahan elit di pekanbaru",
                "Perumahan fasilitas menarik",
                "Perumahan lingkungan bersih",
                "Cluster perumahan eksklusif di Pekanbaru",
                "Premium housing cluster terbaik di Pekanbaru",
                "Perumahan elit Pekanbaru dengan fasilitas lengkap",
                "Rumah dijual di Pekanbaru dengan lokasi strategis",
                "Cari rumah dekat pusat kota Pekanbaru",
                "Hunian strategis di Pekanbaru dekat fasilitas umum",
                "Perumahan dari developer terpercaya di Pekanbaru",
                "Rumah berkualitas dari pengembang tepercaya",
                "Pilihan rumah aman dan legal dari developer berpengalaman",
                "Rumah terbaik untuk investasi di Pekanbaru",
                "Investasi properti menguntungkan di Pekanbaru",
                "Rumah yang cocok untuk investasi jangka panjang",
                "Rumah dengan fasilitas premium di Pekanbaru",
                "Hunian mewah dengan fasilitas bintang lima",
                "Rumah elit lengkap dengan fasilitas eksklusif",
                "Rumah dijual dengan fasilitas terbaik",
                "Hunian modern dan lengkap di Pekanbaru",
                "Cari rumah dengan fasilitas keluarga lengkap",
                "Rumah mewah dengan kolam renang pribadi",
                "Hunian eksklusif dengan swimming pool di Pekanbaru",
                "Rumah impian dengan private pool dan desain elegan",
                "Townhouse modern dengan fasilitas gym dan jogging track",
                "Townhouse dengan taman bermain anak dan keamanan 24 jam",
                "Townhouse mewah dengan CCTV dan club house eksklusif",
                "Perumahan townhouse lengkap dengan fasilitas keluarga",
                "Townhouse dengan keamanan 24 jam dan CCTV",
                "Perumahan dengan sistem keamanan modern",
                "Cluster aman dengan one gate system dan pengawasan penuh",
                "Townhouse dengan taman hijau dan jogging track",
                "Perumahan dengan taman bermain dan area terbuka hijau",
                "Hunian asri dan ramah keluarga di Pekanbaru",
                "Rumah 3 lantai modern di Pekanbaru",
                "Cluster 3 lantai dengan desain elegan dan fungsional",
                "Hunian bertingkat dengan ruang maksimal dan nyaman"
            ],
            'canonical'    => false, // Set to null or 'full' to use Url::full(), set to 'current' to use Url::current(), set false to total remove
            'robots'       => false, // Set to 'all', 'none' or any combination of index/noindex and follow/nofollow
        ],
        /*
         * Webmaster tags are always added.
         */
        'webmaster_tags' => [
            'google'    => null,
            'bing'      => null,
            'alexa'     => null,
            'pinterest' => null,
            'yandex'    => null,
            'norton'    => null,
        ],

        'add_notranslate_class' => false,
    ],
    'opengraph' => [
        /*
         * The default configurations to be used by the opengraph generator.
         */
        'defaults' => [
            'title'       => false, //'Over 9000 Thousand!', // set false to total remove
            'description' => false, //'For those who helped create the Genki Dama', // set false to total remove
            'url'         => false, // Set null for using Url::current(), set false to total remove
            'type'        => false,
            'site_name'   => false,
            'images'      => [],
        ],
    ],
    'twitter' => [
        /*
         * The default values to be used by the twitter cards generator.
         */
        'defaults' => [
            //'card'        => 'summary',
            //'site'        => '@LuizVinicius73',
        ],
    ],
    'json-ld' => [
        /*
         * The default configurations to be used by the json-ld generator.
         */
        'defaults' => [
            'title'       => false, //'Over 9000 Thousand!', // set false to total remove
            'description' => false, //'For those who helped create the Genki Dama', // set false to total remove
            'url'         => false, // Set to null or 'full' to use Url::full(), set to 'current' to use Url::current(), set false to total remove
            'type'        => 'WebPage',
            'images'      => [],
        ],
    ],
];
